import React, { createContext, ReactNode, useContext, useMemo } from 'react';

import { cssStringFromTheme } from '../../css/cssStringFromTheme';
import { ThemeVars } from '../../css/sprinkles.css';
import { lightTheme } from '../../themes/lightTheme';
import { TransactionStoreProvider } from '../../transactions/TransactionStoreContext';
import { AppContext, defaultAppInfo, DisclaimerComponent } from './AppContext';
import { CoolModeContext } from './CoolModeContext';
import { provideRainbowKitChains } from './provideRainbowKitChains';
import {
  RainbowKitChain,
  RainbowKitChainContext,
} from './RainbowKitChainContext';
import { ShowRecentTransactionsContext } from './ShowRecentTransactionsContext';

const ThemeIdContext = createContext<string | undefined>(undefined);
export const ThemeContext = createContext<ThemeVars>(lightTheme());

const attr = 'data-rk';

const createThemeRootProps = (id: string | undefined) => ({ [attr]: id || '' });

const createThemeRootSelector = (id: string | undefined) => {
  if (id && !/^[a-zA-Z0-9_]+$/.test(id)) {
    throw new Error(`Invalid ID: ${id}`);
  }
  return id ? `[${attr}="${id}"]` : `[${attr}]`;
};

export const useThemeRootProps = () => {
  const id = useContext(ThemeIdContext);
  return createThemeRootProps(id);
};

type preTheme = {
  lightMode: ThemeVars;
  darkMode: ThemeVars;
};

export type Theme = ThemeVars | preTheme;

type convert<Theme> = Theme extends ThemeVars ? ThemeVars : preTheme;

/* const convertTheme = (theme: Theme): convert<Theme> => {
  return theme as convert<Theme>;
  } */
const convertTheme = (theme: Theme): ThemeVars => {
  const lightMode = lightTheme();

  if (theme.hasOwnProperty('lightMode')) {
    return lightMode as ThemeVars;
  }
  return theme as ThemeVars;
};

export interface RainbowKitProviderProps {
  chains: RainbowKitChain[];
  id?: string;
  children: ReactNode;
  theme?: Theme;
  showRecentTransactions?: boolean;
  appInfo?: {
    appName?: string;
    learnMoreUrl?: string;
    disclaimer?: DisclaimerComponent;
  };
  coolMode?: boolean;
}

const defaultTheme = lightTheme();

export function RainbowKitProvider({
  chains,
  id,
  theme = defaultTheme,
  children,
  appInfo,
  showRecentTransactions = false,
  coolMode = false,
}: RainbowKitProviderProps) {
  const rainbowkitChains = useMemo(
    () => provideRainbowKitChains(chains),
    [chains]
  );

  if (typeof theme === 'function') {
    throw new Error(
      'A theme function was provided to the "theme" prop instead of a theme object. You must execute this function to get the resulting theme object.'
    );
  }

  const selector = createThemeRootSelector(id);

  const appContext = {
    ...defaultAppInfo,
    ...appInfo,
  };

  const newTheme = convertTheme(theme);

  return (
    <RainbowKitChainContext.Provider value={rainbowkitChains}>
      <CoolModeContext.Provider value={coolMode}>
        <ShowRecentTransactionsContext.Provider value={showRecentTransactions}>
          <TransactionStoreProvider>
            <AppContext.Provider value={appContext}>
              <ThemeIdContext.Provider value={id}>
                {theme ? (
                  <div {...createThemeRootProps(id)}>
                    <style
                      // eslint-disable-next-line react/no-danger
                      dangerouslySetInnerHTML={{
                        // Selectors are sanitized to only contain alphanumeric
                        // and underscore characters. Theme values generated by
                        // cssStringFromTheme are sanitized, removing
                        // characters that terminate values / HTML tags.
                        __html: [
                          `${selector}{${cssStringFromTheme(
                            'lightMode' in theme ? theme.lightMode : theme
                          )}}`,

                          'darkMode' in theme
                            ? `@media(prefers-color-scheme:dark){${selector}{${cssStringFromTheme(
                                theme.darkMode,
                                { extends: theme.lightMode }
                              )}}}`
                            : null,
                        ].join(''),
                      }}
                    />
                    <ThemeContext.Provider value={newTheme}>
                      {children}
                    </ThemeContext.Provider>
                  </div>
                ) : (
                  children
                )}
              </ThemeIdContext.Provider>
            </AppContext.Provider>
          </TransactionStoreProvider>
        </ShowRecentTransactionsContext.Provider>
      </CoolModeContext.Provider>
    </RainbowKitChainContext.Provider>
  );
}
